#!/usr/bin/env python3
"""Generate LaTeX macros and tables from the compact 81-row analysis."""

from __future__ import annotations

import argparse
import csv
import math
from collections import Counter
from fractions import Fraction
from pathlib import Path

try:
    import pandas as pd
except ImportError as exc:  # pragma: no cover
    raise SystemExit("report generation requires pandas") from exc


PROBLEMS = ("misr", "unit_square", "guillotine")
PROBLEM_LABELS = {
    "misr": "MISR",
    "unit_square": "Unit-square",
    "guillotine": "Guillotine",
}
MACRO_PREFIX = {
    "misr": "Misr",
    "unit_square": "UnitSquare",
    "guillotine": "Guillotine",
}

APPENDIX_PROBLEM_LABELS = {
    "misr": "MISR",
    "unit_square": "Unit sq.",
    "guillotine": "Guill.",
}

APPENDIX_LEVEL_LABELS = {
    "endpoint_sequence_pair": "endpoint_seq",
    "triangle_free_rect": "triangle_free",
    "quadratic_program_rectangles": "qp_rect",
    "sequence_pair_pivot": "seq_pivot",
    "lp_dual_pivot": "lp_dual",
    "program_coeff_pivot": "coeff_pivot",
    "exact_lp_gap_pressure": "exact_lp_gap",
    "triangle_free_exact_gap_pressure": "tf_exact_gap",
    "graph_conflict_proxy": "conflict_proxy",
    "square_direct": "square_direct",
    "line_square_incidence": "line_sq_inc",
    "sqstab_exact_grid": "sqstab_grid",
    "coord_mutation": "coord_mut",
    "primal_dual_lines": "primal_dual",
    "sqstab_local_hillclimb": "sqstab_hill",
    "greedy_partial_lp_bitset": "greedy_lp",
    "exact_stab_gap_pressure": "exact_stab_gap",
    "incidence_statistics": "incidence_stats",
    "rect_direct_disjoint": "rect_direct",
    "sequence_pair_packing": "seq_pair_pack",
    "recursive_obstruction_grammar": "obstruction_grammar",
    "packing_resize": "pack_resize",
    "recursive_gadget_assembly": "gadget_assembly",
    "witness_breaking": "witness_break",
    "first_cut_obstruction": "first_cut",
    "depth_limited_dp": "depth_dp",
    "k_subset_nonseparability": "k_subset",
}


def _escape(value) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_\allowbreak{}",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def _code(value) -> str:
    return rf"\code{{{_escape(value)}}}"


def _number(value, digits: int = 4) -> str:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return "--"
    if not math.isfinite(numeric):
        return "--"
    return f"{numeric:.{digits}f}"


def _score(value) -> str:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return "--"
    fraction = Fraction(numeric).limit_denominator(64)
    if abs(float(fraction) - numeric) <= 1e-10:
        if fraction.denominator == 1:
            return rf"${fraction.numerator}$"
        return rf"$\frac{{{fraction.numerator}}}{{{fraction.denominator}}}$"
    return rf"${numeric:.4f}$"


def _hours(value) -> str:
    try:
        return f"{float(value) / 3600.0:.2f}"
    except (TypeError, ValueError):
        return "--"


def _percent(value) -> str:
    try:
        return f"{100.0 * float(value):.1f}"
    except (TypeError, ValueError):
        return "--"


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def _macros(summary: pd.DataFrame, rank: pd.DataFrame, audit_path: Path | None) -> str:
    lines = ["% Generated by scripts/generate_main_matrix_tex.py; do not edit manually."]
    for problem in PROBLEMS:
        row = summary[summary["problem"] == problem].iloc[0]
        prefix = MACRO_PREFIX[problem]
        values = {
            "Rows": int(row["rows"]),
            "Best": _number(row["maximum_score"]),
            "Median": _number(row["median_score"]),
            "Minimum": _number(row["minimum_score"]),
            "QOne": _number(row["q1_score"]),
            "QThree": _number(row["q3_score"]),
            "RowsAtBest": int(row["rows_at_maximum"]),
            "MedianPlateauPercent": f"{100.0 * float(row['median_plateau_fraction']):.1f}",
            "ModelImprovementPercent": f"{100.0 * float(row['model_improvement_fraction']):.1f}",
            "MedianDuplicatesPerGeneration": _number(row["median_duplicates_per_generation"], 2),
            "MedianRepairsPerGeneration": _number(row["median_repairs_per_generation"], 2),
            "MedianModelValidPercent": f"{100.0 * float(row['median_model_valid_fraction']):.1f}",
            "MedianModelTrainCalls": int(round(float(row["median_model_train_calls"]))),
            "TopTimeToBestHours": _hours(row["top_time_to_best_seconds"]),
            "TopBestEpoch": int(float(row["top_best_model_epoch"])),
            "TopItems": int(float(row["top_n_items"])),
        }
        rank25 = rank[
            (rank["problem"] == problem) & (rank["epoch_progress_percent"] == 25)
        ].iloc[0]
        values["RankRhoTwentyFive"] = _number(rank25["spearman_rho"], 3)
        for suffix, value in values.items():
            lines.append(rf"\newcommand{{\{prefix}{suffix}}}{{{value}}}")

    audit_counts = Counter()
    if audit_path is not None and audit_path.exists():
        with audit_path.open(newline="", encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                audit_counts[str(row.get("status") or "unknown")] += 1
    lines.extend(
        [
            rf"\newcommand{{\AuditPassed}}{{{audit_counts.get('passed', 0)}}}",
            rf"\newcommand{{\AuditFailed}}{{{audit_counts.get('failed', 0)}}}",
            rf"\newcommand{{\AuditTotal}}{{{sum(audit_counts.values())}}}",
        ]
    )
    return "\n".join(lines)


def _problem_summary_table(summary: pd.DataFrame) -> str:
    lines = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Overall outcome of the completed 81-cell matrix. Quantiles are across the 27 component configurations, not repeated random seeds.}",
        r"\label{tab:problem-summary}",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"Problem & Min. & Q1 & Median & Q3 & Best & Cells at best \\",
        r"\midrule",
    ]
    for problem in PROBLEMS:
        row = summary[summary["problem"] == problem].iloc[0]
        lines.append(
            " & ".join(
                [
                    PROBLEM_LABELS[problem],
                    _score(row["minimum_score"]),
                    _score(row["q1_score"]),
                    _score(row["median_score"]),
                    _score(row["q3_score"]),
                    _score(row["maximum_score"]),
                    str(int(row["rows_at_maximum"])),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    return "\n".join(lines)


def _top_config_table(metrics: pd.DataFrame, top_n: int = 5) -> str:
    lines = [
        r"\scriptsize",
        r"\begin{longtable}{@{}p{0.08\textwidth}p{0.055\textwidth}p{0.145\textwidth}p{0.145\textwidth}p{0.145\textwidth}rrr@{}}",
        r"\caption{Top five configurations per problem. Epoch is cumulative transformer training epoch; time is elapsed hours to the first appearance of the final best.}",
        r"\label{tab:top-configs}\\",
        r"\toprule",
        r"Problem & Score & Representation & Local search & Surrogate & Epoch & Time & Items \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Problem & Score & Representation & Local search & Surrogate & Epoch & Time & Items \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    for problem in PROBLEMS:
        data = metrics[metrics["problem"] == problem].sort_values(
            ["best_score", "time_to_best_seconds"], ascending=[False, True]
        ).head(top_n)
        for _, row in data.iterrows():
            lines.append(
                " & ".join(
                    [
                        PROBLEM_LABELS[problem],
                        _score(row["best_score"]),
                        _code(row["representation"]),
                        _code(row["local_search"]),
                        _code(row["surrogate"]),
                        str(int(float(row["best_model_epoch"]))) if pd.notna(row["best_model_epoch"]) else "--",
                        _hours(row["time_to_best_seconds"]),
                        str(int(float(row["n_items"]))) if pd.notna(row["n_items"]) else "--",
                    ]
                )
                + r" \\"
            )
        lines.append(r"\addlinespace")
    lines.extend([r"\end{longtable}", r"\normalsize"])
    return "\n".join(lines)


def _factor_tables(marginals: pd.DataFrame) -> dict[str, str]:
    outputs: dict[str, str] = {}
    for problem in PROBLEMS:
        lines = [
            r"\begin{table}[tbp]",
            r"\centering",
            rf"\caption{{Descriptive component marginals for {PROBLEM_LABELS[problem]}. Each level pools nine distinct component cells.}}",
            rf"\label{{tab:{problem.replace('_', '-')}-marginals}}",
            r"\begin{tabularx}{\textwidth}{p{0.16\textwidth}Xrrrrr}",
            r"\toprule",
            r"Factor & Level & Mean & Median & Min. & Max. & IQR \\",
            r"\midrule",
        ]
        data = marginals[marginals["problem"] == problem]
        for factor in ("representation", "local_search", "surrogate"):
            factor_rows = data[data["factor"] == factor].sort_values("mean", ascending=False)
            for index, (_, row) in enumerate(factor_rows.iterrows()):
                lines.append(
                    " & ".join(
                        [
                            factor.replace("_", " ").title() if index == 0 else "",
                            _code(row["level"]),
                            _number(row["mean"]),
                            _number(row["median"]),
                            _number(row["minimum"]),
                            _number(row["maximum"]),
                            f"[{_number(row['q1'])}, {_number(row['q3'])}]",
                        ]
                    )
                    + r" \\"
                )
            lines.append(r"\addlinespace")
        lines.extend([r"\bottomrule", r"\end{tabularx}", r"\end{table}"])
        outputs[problem] = "\n".join(lines)
    return outputs


def _all_rows_table(metrics: pd.DataFrame) -> str:
    lines = [
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.2pt}",
        r"\begin{longtable}{@{}p{0.055\textwidth}p{0.105\textwidth}p{0.10\textwidth}p{0.105\textwidth}rrrrrr@{}}",
        r"\caption{Complete 81-cell result table. Identifiers are shortened here; the full names appear in the design and marginal-effect tables. Plateau is the fraction of completed search generations after the final strict score improvement.}",
        r"\label{tab:all-81}\\",
        r"\toprule",
        r"Prob. & Rep. & Local & Surrogate & Best & Gain & Epoch & h & Plat. (\%) & $n$ \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Prob. & Rep. & Local & Surrogate & Best & Gain & Epoch & h & Plat. (\%) & $n$ \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    for problem in PROBLEMS:
        data = metrics[metrics["problem"] == problem].sort_values(
            ["representation", "local_search", "surrogate"]
        )
        for _, row in data.iterrows():
            lines.append(
                " & ".join(
                    [
                        APPENDIX_PROBLEM_LABELS[problem],
                        _code(APPENDIX_LEVEL_LABELS[row["representation"]]),
                        _code(APPENDIX_LEVEL_LABELS[row["local_search"]]),
                        _code(APPENDIX_LEVEL_LABELS[row["surrogate"]]),
                        _number(row["best_score"]),
                        _number(row["score_gain"]),
                        str(int(float(row["best_model_epoch"]))) if pd.notna(row["best_model_epoch"]) else "--",
                        _hours(row["time_to_best_seconds"]),
                        _percent(row["plateau_fraction"]),
                        str(int(float(row["n_items"]))) if pd.notna(row["n_items"]) else "--",
                    ]
                )
                + r" \\"
            )
        lines.append(r"\addlinespace")
    lines.extend([r"\end{longtable}", r"\setlength{\tabcolsep}{6pt}", r"\normalsize"])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate LaTeX fragments for the final 81-row report.")
    parser.add_argument("analysis_dir", type=Path)
    parser.add_argument("--plot-table-dir", type=Path, required=True)
    parser.add_argument("--audit-csv", type=Path)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args()

    metrics = pd.read_csv(args.analysis_dir / "row_metrics.csv")
    summary = pd.read_csv(args.plot_table_dir / "problem_summary.csv")
    marginals = pd.read_csv(args.plot_table_dir / "factor_marginals.csv")
    rank = pd.read_csv(args.plot_table_dir / "early_final_rank.csv")

    _write(args.out_dir / "analysis_values.tex", _macros(summary, rank, args.audit_csv))
    _write(args.out_dir / "table_problem_summary.tex", _problem_summary_table(summary))
    _write(args.out_dir / "table_top_configs.tex", _top_config_table(metrics))
    for problem, table in _factor_tables(marginals).items():
        _write(args.out_dir / f"table_{problem}_marginals.tex", table)
    _write(args.out_dir / "table_all_81.tex", _all_rows_table(metrics))
    print(f"wrote LaTeX fragments to {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
