from __future__ import annotations

from random import Random
from typing import Any, Protocol

from formulaboost.core.objects import MathObject


class Domain(Protocol):
    name: str

    def validate(self, obj: MathObject) -> bool: ...

    def score(self, obj: MathObject) -> float: ...

    def normalize_score(self, score: float, params: dict[str, Any]) -> float: ...

    def random_object(self, params: dict[str, Any], rng: Random) -> MathObject: ...

    def greedy_object(self, params: dict[str, Any], rng: Random) -> MathObject: ...

    def local_repair(self, obj: MathObject, budget: int, rng: Random) -> MathObject: ...

    def canonicalize(self, obj: MathObject) -> str: ...

    def invariants(self, obj: MathObject) -> dict[str, Any]: ...

    def similarity(self, obj_a: MathObject, obj_b: MathObject) -> float: ...
